/*
================================================================================================
  MODULE ARCHITECTURE OVERVIEW: Pipeline Memory Access Stage (MEM Stage)
================================================================================================
  The Memory stage bridges the high-speed CPU pipeline with the Data Memory (SRAM/RAM). 
  Its major responsibility is executing Load and Store instructions (`LW`, `SW`, `LB`, `SB`, etc.).

  KEY DESIGN CONSTRAINT: This core assumes a synchronous RAM port. 
  When you request data from a synchronous RAM, the data does NOT appear instantly; it arrives 
  exactly 1 clock cycle later. Therefore, this module splits load operations into two halves:
    1. Address Phase (Combinational request sent out to RAM).
    2. Data Phase (Flops saved to match the incoming data on the next clock edge).
================================================================================================
*/

`ifdef CUSTOM_DEFINE
    `include "defines.vh"
`endif

module mpt_MEM_stage
    `include "mpt_definitions.vh"
    (
    input  wire                 clk_i,             // Master system clock
    input  wire                 resetn_i,          // Active-low synchronous reset

    // =========================================================================================
    //                        DATA MEMORY INTERFACE (To RAM Array)
    // =========================================================================================
    output reg   [31:0]        DMEM_addr_o,       // Word-aligned 32-bit physical address bus
    output reg   [3:0]         DMEM_wr_byte_en_o, // 4-bit lane strobe (Strobes individual bytes inside a 32-bit word)
    output reg   [31:0]        DMEM_wr_data_o,    // Data payload being written out to memory
    output reg                 DMEM_rst_o,        // Synchronous reset signal for RAM block peripherals
          
    // =========================================================================================
    //                        PIPELINE REGISTER OUTPUTS (To WB Stage)
    // =========================================================================================
    output reg   [31:0]        MEM_dout_o,        // Final read data payload (masked and sign-extended)
    output reg                 MEM_memtoreg_o,    // Control signal forwarded to Writeback selector Mux
    output reg   [31:0]        MEM_alu_result_o,  // Pass-through of calculation address / arithmetic values
    output reg                 MEM_rd_wr_en_o,    // Register File Write Enable signal passed to WB stage
    output reg   [4:0]         MEM_rd_addr_o,     // Destination register address (x0-x31) passed to WB stage
    output reg                 MEM_exception_o,   // Architectural trap wire (asserts on unaligned memory access)

    // =========================================================================================
    //                        DATA MEMORY INPUTS (From RAM Array)
    // =========================================================================================
    input  wire  [31:0]        DMEM_rd_data_i,    // Raw 32-bit data block read back from RAM

    // =========================================================================================
    //                            HAZARD FORWARDING INTERFACE
    // =========================================================================================
    input  wire                ForwardM_i,        // Forwarding control line: resolves Memory-to-Memory hazards 
                                                // (e.g., loading a value from memory and instantly storing it)

    // =========================================================================================
    //                        PIPELINE INPUTS (Coming from EX Stage)
    // =========================================================================================
    input  wire                EX_mem_wr_en_i,    // Core write demand flag passed from execution block
    input  wire  [3:0]         EX_mem_op_i,       // Size/Sign encoding code describing load/store layout
    input  wire                EX_memtoreg_i,     // Writeback destination routing map marker
    input  wire  [31:0]        EX_alu_result_i,   // Calculated raw byte address generated by the ALU
    input  wire  [31:0]        EX_rs2_data_i,     // Original data payload sourced from register rs2 for storage
 
    input  wire                EX_rd_wr_en_i,     // Destination register write authorization tracking
    input  wire  [4:0]         EX_rd_addr_i,      // Target register destination identifier
    input  wire                EX_exception_i     // Upstream pipeline fault tracking token
    );
    

// =============================================================================================
//                       INTERNAL STORAGE & REGISTERS
// =============================================================================================
    reg        misaligned_store; // Set to 1 if a halfword store breaks boundaries (e.g., address ends in 2'b01 or 2'b11)
    reg        misaligned_load;  // Set to 1 if a halfword load breaks boundaries (e.g., address ends in 2'b01 or 2'b11)
    reg [31:0] wr_data;          // Intermediate variable holding store payload after hazard check
    reg [3:0]  byte_en;          // Internal combinational byte-mask tracking matrix
    reg [3:0]  mem_op;           // Flop storage tracking the operation type for the 1-cycle latency load loop
    reg [1:0]  byte_addr;        // Flop storage tracking the exact lower offset bits for incoming read data processing

// =============================================================================================
//                                   IMPLEMENTATION
// =============================================================================================

    // =========================================================================================
    // 1. PIPELINE BOUNDARY REGISTERS (MEM to WB)
    // =========================================================================================
    // Synchronously latches data at the clock edge to move everything cleanly down the pipeline.
    always@(posedge clk_i) begin
        if(resetn_i == 1'b0) begin
            MEM_memtoreg_o     <= 0;
            MEM_alu_result_o   <= 0;
            MEM_rd_wr_en_o     <= 0;
            MEM_rd_addr_o      <= 0;
            MEM_exception_o    <= 0;
        end
        else begin
            MEM_memtoreg_o     <= EX_memtoreg_i;
            MEM_alu_result_o   <= EX_alu_result_i;
            MEM_rd_wr_en_o     <= EX_rd_wr_en_i;
            MEM_rd_addr_o      <= EX_rd_addr_i;
            // Capture any upstream fault OR trigger an exception if a misaligned store/load is caught here
            MEM_exception_o    <= EX_exception_i || misaligned_store || misaligned_load;
        end
    end
    
    
    // =========================================================================================
    // 2. RAM BUS CONTROL GENERATOR
    // =========================================================================================
    always@* begin
        // CRITICAL HARDWARE DETAIL: Physical 32-bit block RAM arrays are word-addressed.
        // We force the lowest two bits to 2'b00. This aligns the address bus to a clean 
        // 4-byte boundary, preventing unaligned hardware communication errors.
        DMEM_addr_o       = {EX_alu_result_i[31:2], 2'b0}; 
        
        // Invert the active-low reset signal to drive standard active-high RAM array resets
        DMEM_rst_o        = ~resetn_i;
        
        // Strobe byte lanes only if a memory write operation is actively requested by the pipeline
        DMEM_wr_byte_en_o = (EX_mem_wr_en_i) ? byte_en : 4'b0;
    end


    // =========================================================================================
    // 3. STORE HAZARD FORWARDING MULTIPLEXER
    // =========================================================================================
    // Resolves memory hazards. If an instruction currently in the Writeback stage is trying to 
    // save a value that this Store instruction needs to write, intercept it via `ForwardM_i`.
    always@* begin
        if(ForwardM_i)
            wr_data = MEM_alu_result_o; // Grab the newly minted result directly from the pipeline wall
        else 
            wr_data = EX_rs2_data_i;    // Standard pathway: use data fetched from register rs2
    end


    // =========================================================================================
    // 4. DATA MEMORY STORE LAYOUT MANIPULATION (SW, SB, SH) & LOAD ALIGNMENT CHECK
    // =========================================================================================
    // Unclocked combinational block shifting and formatting values into their correct positions 
    // inside the 32-bit RAM word based on the target offset.
    // ALSO checks for misalignment in both Load and Store operations.
    always@* begin
        // Establish safe baseline defaults
        DMEM_wr_data_o   = 32'b0; 
        misaligned_store = 0;
        misaligned_load  = 0;  // Initialize load misalignment flag
        byte_en          = 4'b0;

        case(EX_mem_op_i)

            // Store Word (32-bit): Write all 4 bytes simultaneously across the interface.
            `MEM_SW: begin
                DMEM_wr_data_o = wr_data;
                byte_en        = 4'b1111; // Activate all four byte-lane strobe lines
                // FIX: SW must be word-aligned (offset 2'b00). Any other lower
                // address bits represent an unaligned store and must trap.
                if (EX_mem_wr_en_i && (EX_alu_result_i[1:0] != 2'b00))
                    misaligned_store = 1;
            end

            // Store Byte (8-bit): Shift the isolated bottom byte into the correct slot 
            // matching the lower address offset.
            `MEM_SB: begin
                case(EX_alu_result_i[1:0]) 
                    2'b00: begin
                        DMEM_wr_data_o = { {24{1'b0}}, wr_data[7:0] }; 
                        byte_en        = 4'b0001; // Enable Byte Lane 0
                    end
                    2'b01: begin
                        DMEM_wr_data_o = { {16{1'b0}}, wr_data[7:0], {8{1'b0}} };
                        byte_en        = 4'b0010; // Enable Byte Lane 1
                    end
                    2'b10: begin
                        DMEM_wr_data_o = { {8{1'b0}},  wr_data[7:0], {16{1'b0}} };
                        byte_en        = 4'b0100; // Enable Byte Lane 2
                    end
                    2'b11: begin
                       DMEM_wr_data_o = { wr_data[7:0], {24{1'b0}} };
                       byte_en        = 4'b1000; // Enable Byte Lane 3
                    end
                endcase
            end 

            // Store Half-Word (16-bit): Position two bytes into either the lower or upper half of the word.
            `MEM_SH: begin
                case(EX_alu_result_i[1:0])
                    2'b00: begin
                       DMEM_wr_data_o = { {16{1'b0}}, wr_data[15:0] };
                       byte_en        = 4'b0011; // Enable Byte Lanes 0 and 1
                    end
                    2'b10: begin
                       DMEM_wr_data_o = { wr_data[15:0], {16{1'b0}} };
                       byte_en        = 4'b1100; // Enable Byte Lanes 2 and 3
                    end
                    // TRAP TRIGGER: mpt does not support unaligned accesses. 
                    // Storing a half-word at an odd index (2'b01 or 2'b11) trips the error flag.
                    default: if (EX_mem_wr_en_i) misaligned_store = 1;
                endcase 
            end   

        endcase

        // FIX: Misaligned-load detection. The original code declared the
        // 'misaligned_load' flag but never asserted it, so misaligned LH/LW
        // silently returned wrong data instead of trapping. We now flag any
        // halfword load whose offset is odd (LSB == 1) and any word load
        // whose offset is not 2'b00 as misaligned, matching RV32I semantics.
        if (EX_mem_rd_en_i) begin
            case (EX_mem_op_i)
                `MEM_LH, `MEM_LH_U: if (EX_alu_result_i[0]    != 1'b0) misaligned_load = 1;
                `MEM_LW:            if (EX_alu_result_i[1:0]  != 2'b00) misaligned_load = 1;
                default: ; // LB/LBU are byte-granular: always aligned
            endcase
        end
    end
    

    // =========================================================================================
    // 5. DATA MEMORY LOAD CONTROL LATENCY ALIGNMENT
    // =========================================================================================
    // Because memory takes 1 full clock cycle to return read values, we must save the operation 
    // configuration and target offset in registers so they are available when the data arrives.
    always@(posedge clk_i) begin
        if(resetn_i == 1'b0) begin
            mem_op    <= 0;
            byte_addr <= 0;
        end else begin
            mem_op    <= EX_mem_op_i;        // Cache the load size profile type
            byte_addr <= EX_alu_result_i[1:0]; // Cache the offset location configuration
        end        
    end

    // =========================================================================================
    // 6. LOAD EXTRACTION & SIGN EXTENSION GENERATOR (LB, LH, LW, LBU, LHU)
    // =========================================================================================
    // Unclocked combinational block that snipes the desired bytes out of the raw 32-bit RAM word 
    // and pads them appropriately to fill the CPU's internal 32-bit register width.
    always@* begin
        case(mem_op)
            
            // Load Byte (Signed): Pulls out 8 bits and copies the sign bit (bit 7) across the remaining 24 bits.
            `MEM_LB: begin
                case(byte_addr)
                    2'b00: MEM_dout_o = { {24{DMEM_rd_data_i[7]}},   DMEM_rd_data_i[7:0] }; 
                    2'b01: MEM_dout_o = { {24{DMEM_rd_data_i[15]}},  DMEM_rd_data_i[15:8] }; 
                    2'b10: MEM_dout_o = { {24{DMEM_rd_data_i[23]}},  DMEM_rd_data_i[23:16] }; 
                    2'b11: MEM_dout_o = { {24{DMEM_rd_data_i[31]}},  DMEM_rd_data_i[31:24] }; 
                endcase
            end

            // Load Half-Word (Signed): Pulls out 16 bits and copies the sign bit across the remaining 16 bits.
            `MEM_LH: begin
                case(byte_addr[1])
                    0: MEM_dout_o = { {16{DMEM_rd_data_i[15]}}, DMEM_rd_data_i[15:0] };
                    1: MEM_dout_o = { {16{DMEM_rd_data_i[31]}}, DMEM_rd_data_i[31:16] };
                endcase
            end

            // Load Byte Unsigned (Zero-Extended): Extracts 8 bits and pads the upper 24 bits with 0s.
            `MEM_LB_U: begin
                case(byte_addr)
                    2'b00: MEM_dout_o = { {24{1'b0}}, DMEM_rd_data_i[7:0] }; 
                    2'b01: MEM_dout_o = { {24{1'b0}}, DMEM_rd_data_i[15:8] }; 
                    2'b10: MEM_dout_o = { {24{1'b0}}, DMEM_rd_data_i[23:16] }; 
                    2'b11: MEM_dout_o = { {24{1'b0}}, DMEM_rd_data_i[31:24] }; 
                endcase
            end
            
            // Load Half-Word Unsigned (Zero-Extended): Extracts 16 bits and pads the upper 16 bits with 0s.
            `MEM_LH_U: begin
                case(byte_addr[1])
                    0: MEM_dout_o = { {16{1'b0}}, DMEM_rd_data_i[15:0] };
                    1: MEM_dout_o = { {16{1'b0}}, DMEM_rd_data_i[31:16] };
                endcase
            end

            // Load Word (32-bit): Direct bypass. Passes the full raw 32-bit block cleanly into the pipeline.
            `MEM_LW: begin
                MEM_dout_o = DMEM_rd_data_i;
            end

            // Safety catch fallback
            default: MEM_dout_o = DMEM_rd_data_i;
        endcase
    end
    
endmodule